[package]
name = "tauthesis"
version = "0.3.1"
entrypoint = "main.typ"
authors = ["Santtu Söderholm <santtu.soderholm@tuni.fi>"]
license = "MIT"
description = "A template for writing Tampere University theses."
homepage = "https://gitlab.com/tuni-official/thesis-templates/tau-typst-thesis-template"
repository = "https://gitlab.com/tuni-official/thesis-templates/tau-typst-thesis-template"
keywords = ["Tampere University", "thesis template"]
categories = ["thesis", "layout"]
disciplines = ["education"]
compiler = "0.11.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
